import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from '../components/hero'
import Navbar from '../components/navbar'
import apperal from '../assets/apparel.png'
import wraps from '../assets/Wraps1.png'
import { SiHeadspace } from 'react-icons/si'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>FAFO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Hero></Hero>
      <section className='w-full sm:flex'>
        <div className='sm:w-1/2 '>
          <a className='hover:cursor-pointer'>
        <Image src={apperal} className='sm:h-full'/>
        </a>
        </div>
        <div className='sm:w-1/2 '>
          <a className='hover:cursor-pointer'>
        <Image src={wraps} className='sm:h-full '/>
        </a>
        </div>
      </section>
      <section>
        <div className='bg-black'>
          <h1 className='text-6xl flex justify-left pl-10 text-white'> 
          FA<SiHeadspace className="w-4 flex"/>FO
          </h1>
          <h2 className='flex justify-left pl-10 underline text-5xl text-white '>
            Fuck Around  Find Out 
          </h2>
          </div>
          <div className=''>
          <p className='font-bold text-3xl  p-4  text-center text-white bg-black'>
          When the concept of FAFO came to me, I didnt want to simply be another small clothing line. I wanted to incorporate my personal beliefs and style in the very fiber of the companies being. While the name FAFO( Fuck Around Find Out ) was meant to be a way of standing out from the crowd, I feel in love with the name more and more as it truly captured the pure choas that it my mind. <br/>
           For so long society has tried to tell us what is acceptable and how to behave, dress and think. It has taught us to depend on the strength on others, to never take matters into our own hands. It has made us weak, in both mind and body. 
            FAFO is meant for those who see a problem and instead of shying away or calling for help they stand their ground and face it head on. It is meant for those who are willing tot hink outside the box to find their own truths. It is meant for those who will not bend in their resolve, those who dont not far walking the long and lonely road to find their greater purpose. <br/> 
           We live in a country founded by men who dared to challenge the status que, at the risk of death, public shame/ridicule and still forged on. Hundreds of years later we have forgotten the lessons our founding father taught us. We have forgotten how every day men and women chose to stand and fight for what they knew to be right. Human history is defined by the victor, not by the sheep. 
            
            FAFO is not for the sheep, nor is it for the wolves who prey on the weak. FAFO is for the wardens, the shields, the thinkers and the free minds. It is for those who are willing to fight, not because they must but for the simple reason of because it is right. It is for those who will defend the weak, regardless of race, religion, creed or orientation. It is for those who see the world for what it is, for all its wrongs and rights, and accept it but never settle. It is for those who look fear in the face and simply<br />                           
          </p>
          <h3 className='font-medium text-center text-5xl bg-black text-white'>
                                                                  "Fuck Around and Find Out"
            </h3>
          </div>
      
      </section>
      
    </>
  )
}
